spring:
  cloud:
    gateway:
      routes:
        - id: stores
          uri: lb://stores
          predicates:
            - Path=/stores/**
        - id: rest
          uri: lb://rest
          predicates:
            - Path=/**
server:
  port: 8800